name: actions workflow

on: push

jobs:
  run-javascript-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Application
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Nag
      - name: log greeting time 
        run: echo "${{ steps.greet.outputs.time }}"
