name: matrix

on: push

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v2
    
    - name: run a one-line script 
      run: echo Hello, World!
    - name: run a multi-line script
      run: |
        echo add another action to build
        echo test, and deploy your project
        