name: shell commands

on: [pull_request]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world"
      - name: multi line command
        run: |
          node -v 
          npm -v
      - name: run python
        run: |
          import platform
          print(platform.processor())
        shell: python

  run-poweshell-commands:
    runs-on: windows-latest
    needs: ["run-shell-commands"]
    steps:
      - name: directory shell
        run: Get-Location
      - name: working directory
        run: pwd 
        shell: bash